image: Visual Studio 2015

environment:
  matrix:
    - tbs_arch: "x64"
      tbs_tools: "msvc14"
      tbs_static_runtime: 0

    - tbs_arch: "x32"
      tbs_tools: "mingw"
      tbs_static_runtime: 0

matrix:
  allow_failures:
    - tbs_tools: "mingw"

branches:
  except:
    - osx-deploy

init:
  - set BUILD_TYPE=release
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin;

install:
  # Submodules are not cloned by default
  - git submodule update --init --recursive

build_script:
  - if [%tbs_tools%]==[msvc14] if [%tbs_arch%]==[x64] SET PATH=%PATH%;C:\Qt\5.9\msvc2015\bin;
  - if [%tbs_tools%]==[mingw] if [%tbs_arch%]==[x32] SET PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin;C:\Qt\5.9.5\mingw53_32\bin;
  - echo "catchTests=false" > globals.pri
  - qmake cuteproject.pro -r CONFIG+=%BUILD_TYPE%
  - jom
  - jom clean

after_build:
  - ps: Get-ChildItem -rec -include *.exe,*.dll,*.lib,*.gcda,*.gcno
#  - ps: dumpbin /dependents .\app\$env:BUILD_TYPE\cuteproject.exe
  - ps: windeployqt app\$env:BUILD_TYPE\cuteproject.exe
  - ps: md -Force cuteproject
  - ps: Copy-Item -Path app\$env:BUILD_TYPE -Destination cuteproject â€“Recurse
  - 7z a -r cuteproject-windows_x86.zip cuteproject

artifacts:
  - path: cuteproject-*.zip
