language: cpp
os:
  - linux
  - osx
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
branches:
  only:
  - master
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qt5-qmake gdb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH ; fi
script:
  - qmake cuteproject.pro -r CONFIG+=debug
  - make
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make distclean ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "catchTests=false" > globals.pri ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake cuteproject.pro -r CONFIG+=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x pkgs/macOS.sh && pkgs/macOS.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) ; fi
